# Site settings
title: Roger Perales Mares
email: rogerperalesmares493@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "Portfolio" # the subpath of your site, e.g. /blog/
url: "https://ryuggha.github.io/" # the base hostname & protocol for your site

itch.io_username: Ryuggha
github_username: Ryuggha

# Build settings
markdown: kramdown
